### ISSUE TITLE
Cannot start ncpa_listener Solaris 11.3

### ISSUE THREAD

**Issue by inakimtz** [NagiosEnterprises/ncpa#633]
After install ncpa-2.2.1.sol11.i86pc.pkg in Solaris 11.3, cannot start ncpa_listener.
OpenSSL version = OpenSSL 1.0.1p 9 Jul 2015

[ May 11 10:39:24 Executing start method ("/usr/local/ncpa/ncpa_listener"). ]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "ncpa_listener.py", line 11, in <module>
  File "/root/ncpa/agent/listener/certificate.py", line 2, in <module>
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/crypto.py", line 12, in <module>
  File "/usr/local/lib/python2.7/site-packages/cryptography/x509/__init__.py", line 7, in <module>
ImportError: cannot import name certificate_transparency
[ May 11 10:39:24 Method "start" exited with status 1. ]

**Comment by jomann09** [comment]
How are you starting ncpa? what command are you using?

**Comment by jomann09** [comment]
This package seems to have been the issue, re-building the package fixed the issue. I've uploaded the new pacakge and it seems to work on both Solaris 11.3 and 11.4 now.
