### ISSUE TITLE
NCPA 2.2.1 on Solaris 11.4: Exception on /api/cpu/percent/

### ISSUE THREAD

**Issue by ljlapierre** [NagiosEnterprises/ncpa#622]
When running the ncpa_passive daemon with a CPU check, I get the following output. I ran with logging set to debug, it's as verbose as I can get it.
```
2020-03-09 15:01:01,662 6035 INFO Running check: cpu/percent aggregate=avg -w 80 -c 90
2020-03-09 15:01:02,201 6035 ERROR Exception on /api/cpu/percent/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
  File "/root/ncpa/agent/listener/server.py", line 185, in token_auth_decoration
  File "/root/ncpa/agent/listener/server.py", line 951, in api
  File "/usr/local/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
AttributeError: 'Request' object has no attribute 'is_xhr'
2020-03-09 15:01:02,219 6035 ERROR Error with JSON: No JSON object could be decoded. JSON was: <!DOCTYPE html>
<html lang='en'>
...
    <p style="font-size: 1.8rem;">There was a internal server error. Please contact your system administrator.</p>
...
</html>
2020-03-09 15:01:02,219 6035 ERROR Stdout or returncode was None, cannot return meaningfully.
Traceback (most recent call last):
  File "ncpa_passive.py", line 51, in run_all_handlers
  File "/root/ncpa/agent/passive/nrdp.py", line 115, in run
  File "/root/ncpa/agent/passive/nrdp.py", line 97, in get_xml_of_checkresults
  File "/root/ncpa/agent/passive/nrdp.py", line 56, in make_xml
  File "/root/ncpa/agent/passive/ncpacheck.py", line 84, in run
ValueError: Stdout or returncode was None, cannot return meaningfully.
```

**Comment by jomann09** [comment]
I will take a look at this, I think it's because when it was built it was using improper packages. I should be able to build a new version with fixes this week.

**Comment by jomann09** [comment]
Is this on the latest version on sparc or x86? I am  testing this now and with the new build I had to make to ensure it properly worked on 11.3/11.4 you should re-install the pacakge from: https://assets.nagios.com/downloads/ncpa/ncpa-latest.sol11.i86pc.pkg

**Comment by ljlapierre** [comment]
I tested this on 2.2.1 on SPARC hardware, not x86

**Comment by jomann09** [comment]
I will have to rebuild for SPARC also, so I will get back to you on that shortly.

**Comment by jomann09** [comment]
If you want to try it, you can try on https://assets.nagios.com/downloads/ncpa/ncpa-latest.sol11.sparc.pkg and let me know (I think it works because we set werkzug to the proper version since it needed to be rebuilt for Solaris 11.3 so let me know if you try it with the passive checks)

**Comment by dharman0125** [comment]
I'm seeing the same issue for any call into the /api space on a sparc 11 system using the 2.2.1 agent.  I see that this bug was removed from 2.2.2 and it's not available yet for Solaris anyways.

**Comment by ljlapierre** [comment]
I gave this a go on NCPA 2.2.2, the CPU-specific error is gone but a similar issue is present with swap. See below.

Would you like this issue closed and a new open? Or shall we continue with this one?

```
2020-10-14 15:30:59,189 2909 INFO started
2020-10-14 15:31:03,018 2909 INFO Running check: cpu/percent aggregate=avg -w 80 -c 90
2020-10-14 15:31:03,539 2909 INFO Running check: disk/logical/| -w 80 -c 90
2020-10-14 15:31:03,769 2909 INFO Running check: memory/virtual -u Gi -w 80 -c 90
2020-10-14 15:31:04,311 2909 INFO Running check: memory/swap -u Gi -w 50 -c 80
2020-10-14 15:31:04,338 2909 ERROR Exception on /api/memory/swap/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
  File "/root/ncpa/agent/listener/server.py", line 185, in token_auth_decoration
  File "/root/ncpa/agent/listener/server.py", line 946, in api
  File "/root/ncpa/agent/listener/nodes.py", line 97, in run_check
  File "/root/ncpa/agent/listener/nodes.py", line 276, in get_values
  File "/root/ncpa/agent/listener/psapi.py", line 148, in <lambda>
  File "/usr/local/lib/python2.7/site-packages/psutil/__init__.py", line 2108, in swap_memory
  File "/usr/local/lib/python2.7/site-packages/psutil/_pssunos.py", line 160, in swap_memory
ValueError: invalid literal for int() with base 10: 'yes'
2020-10-14 15:31:04,357 2909 ERROR Error with JSON: No JSON object could be decoded. JSON was: <!DOCTYPE html>
<html lang='en'>
	<redacted, no useful info>
</html>
2020-10-14 15:31:04,357 2909 ERROR Stdout or returncode was None, cannot return meaningfully.
Traceback (most recent call last):
  File "ncpa_passive.py", line 51, in run_all_handlers
  File "/root/ncpa/agent/passive/nrdp.py", line 115, in run
  File "/root/ncpa/agent/passive/nrdp.py", line 97, in get_xml_of_checkresults
  File "/root/ncpa/agent/passive/nrdp.py", line 56, in make_xml
  File "/root/ncpa/agent/passive/ncpacheck.py", line 84, in run
ValueError: Stdout or returncode was None, cannot return meaningfully.
2020-10-14 15:31:05,359 2909 INFO Running check: memory/swap -u Gi -w 50 -c 80
2020-10-14 15:31:05,407 2909 ERROR Exception on /api/memory/swap/ [GET]
```

**Comment by ljlapierre** [comment]
We've decided to disable swap monitoring, as we we're getting any value out of it. The /api/cpu/percent/ bug is completely gone with version 2.2.2, I'll close this bug.

If others are finding issues with swap and you'd like help troubleshooting feel free to reach out to me, but it could just as easily be a bug in Solaris, and I don't care enough to go down the rabbit hole for something we don't care to monitor anymore.

Thanks for all of your help!

**Comment by jomann09** [comment]
Just for the record, the swap issue will be fixed in 2.3.0 since there was an issue in psutils that was causing it, and we submitted a fix and it should be in the next version of psutils which will be in the next version of NCPA.
