### ISSUE TITLE
Custom plugins give errors after updating from 2.1.1 to 2.1.2

### ISSUE THREAD

**Issue by barth-topdesk** [NagiosEnterprises/ncpa#435]
After the update to ncpa agent 2.1.2 on our client machines the following error occurs when running custom plugins:

> 
> 2018-02-28 08:59:49,847 1827 INFO stopped
> 2018-02-28 08:59:50,982 11376 INFO started
> 2018-02-28 08:59:51,004 11376 INFO Using SSL version TLSv1
> 2018-02-28 08:59:53,938 11376 ERROR 'PluginNode' object has no attribute 'title'
> Traceback (most recent call last):
>   File "/root/ncpa/agent/listener/nodes.py", line 305, in run_check
>   File "/root/ncpa/agent/listener/nodes.py", line 336, in get_nagios_return
> AttributeError: 'PluginNode' object has no attribute 'title'
> 2018-02-28 08:59:53,944 11376 INFO 10.231.155.33 - - [2018-02-28 08:59:53] "GET /api/plugins/check_puppet_run.py/?token=xxxxxxxxxxxxx&check=1 HTTP/1.1" 200 226 0.033851
> 2018-02-28 09:01:12,411 11376 ERROR 'PluginNode' object has no attribute 'title'
> Traceback (most recent call last):
>   File "/root/ncpa/agent/listener/nodes.py", line 305, in run_check
>   File "/root/ncpa/agent/listener/nodes.py", line 336, in get_nagios_return
> AttributeError: 'PluginNode' object has no attribute 'title'
> 2018-02-28 09:01:12,417 11376 INFO 10.232.155.16 - - [2018-02-28 09:01:12] "GET /api/plugins/check_ntp_time/-H/%22xxxxxxxxxxxxxc%22/-w/5/-c/30?token=xxxxxxxxxxxxx&check=1 HTTP/1.1" 200 226 0.024264
>

**Comment by jvandermeulen** [comment]
Unfortuntely we have the same issue, even with _**check_ncpa.py**_ version 1.1.3.
However browsing through the Web GUI and navigating to API Endpoint "plugins" all plugins are running smooth.

**Comment by centinel** [comment]
We're experiencing this issue as well. Like @jvandermeulen we are able to run plugins normally through the web GUI.

**Comment by jomann09** [comment]
I had tested this, are you running it through the check_ncpa.py and having issues or through the GUI?

**Comment by centinel** [comment]
I'm running it through the latest version of check_ncpa.py.

> [root@nagios libexec]# python check_ncpa.py -H some-host.mydomain.com -t 'mykey' -P 5693 -M 'plugins/check_service.py' -q "args=auditd" -v
> Connecting to: https://some-host.mydomain.com:5693/api/plugins/check_service.py/?token=mykey&check=1&args=auditd
> File returned contained:
> {
>     "returncode": 3, 
>     "stdout": "'PluginNode' object has no attribute 'title'"
> }
> 'PluginNode' object has no attribute 'title'

**Comment by jomann09** [comment]
Thanks I did figure out what the issue was. Some problems when moving the get_values() function which really shouldn't be done the way it is. Anyway it caused it to not run the plugin execution nagios return values so that is the issue. I'll rebuild it now as 2.1.3 - sorry for the problems.

**Comment by jomann09** [comment]
Closing this, 2.1.3 is out. Tested this so should be good this time.
